name: Build and Release

on:
  push:
    tags:
      - 'v*' # Triggers workflow only when you push a tag starting with 'v' (e.g., v1.2)

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build with MSBuild
      run: msbuild SHALLControl.csproj /p:Configuration=Release

    - name: Zip the Output
      run: Compress-Archive -Path .\bin\Release\* -DestinationPath update.zip

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: update.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
